version: '3'
services:
  db:
    image: postgres:12.0
    volumes:
      - ./tmp/db:/var/lib/postgresql/data

  test: &app
    image: roborregos/dashboard:1.0
    build: .
    command: rspec
    volumes:
      - .:/app
    depends_on:
      - db
    environment: &app_environment
      RAILS_ENV: 'test'

  web:
    <<: *app
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - "3000:3000"
    environment:
      RAILS_ENV: 'development'
